### PR TITLE
Fix empty context array when directly browsing to an URL

### LINKED ISSUE #15: Opening an article in a new tab or window displays a blank page
Title is self explanatory. Right-click -> "Open in a new tab/window" displays a blank page instead of the article.
Issue happens on both Chrome Version 105/106 and Firefox Version 105 on Windows 10.

**Details:**
- OS: Windows 10
- npm version: 8.19.1
- node version: 18.9.1

### PR DESCRIPTION
**Pull request by gbrivady**
Fixes #15 and #44 

Basically implemented the fix suggested by @atxr in #44, with proper async'ing of functions and stuff

### CODE REVIEW

**Comment by amtoine** [comment]
i added #44 to the links, you forgot it :wink:

**Comment by ctmbl** [comment]
Thanks for this fix it was pretty annoying! I'm quite busy right now but I'll look into it as soon as I can!

File: frontend/src/pages/blog/Article.js [hunk 1]
```diff
@@ -4,9 +4,28 @@ import { useArticlesContext } from "../../hooks/useArticlesContext";
...
+        const article = await response.json();
+        dispatch({ type: "ADD", payload: article });       // if it exists, add it to the ArticlesContext
+        return article;
+      }
+      else {
+        return null;
+      } 
+  };
+  
+  try {
```
Comment (atxr) [inline frontend/src/pages/blog/Article.js:21]: Just some minor comments here:
- I would use `let` instead of `const`
- You should move this return outside of the try/catch
- I found a cleaner way to do `filter(...)[0]`

```js
let article;
try {
    article = articles.find((a) => a._id === id);
} catch (error) {  //if articles are null, articles.filter produces an error
    article = fetchArticle();
}

return <ArticleView article={article} />;
```

**Review by atxr — CHANGES_REQUESTED** [review]
Thanks for the implementation!
I added few suggestions, and I will test once they will be solved.

File: frontend/src/context/ArticleContext.js [hunk 2]
```diff
@@ -10,9 +10,10 @@ export const articlesReducer = (state, action) => {
       };
 
     case "ADD":
-      return {
-        articles: [action.payload, ...state.articles],
-      };
+      if (state.articles == null) {
+        return {articles: [action.payload], }; //cannot iterate over null
+      }
+      return {articles: [action.payload, ...state.articles], };
```
Comment (ctmbl) [inline frontend/src/context/ArticleContext.js:16]: Perhaps you could do something like
```js
return state.articles ? {articles: [action.payload, ...state.articles], } : {articles: [action.payload], };
```
or something using the [`??` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing)

Maybe it would sacrifice too much the code clearness :confused: 

At least we could use a `===` instead of  `==`
But I'm not quite sure so once again @atxr :smiling_face_with_tear: ?

Comment (ctmbl) [reply frontend/src/context/ArticleContext.js:16]: My bad I actually didn't quite understand the real problem, see my other thread on `dispatch` call!

File: frontend/src/pages/blog/Article.js [hunk 3]
```diff
@@ -4,9 +4,28 @@ import { useArticlesContext } from "../../hooks/useArticlesContext";
...
-  const { articles } = useArticlesContext();
-  const article = articles.filter((a) => a._id === id)[0];
-  return <ArticleView article={article} />;
+  const { articles, dispatch } = useArticlesContext();
+
+  const fetchArticle = async () => {
+      const response = await fetch(`/api/articles/${id}`);  // fetch the article (only this one) from the database
+      if (response.ok) {
+        const article = await response.json();
+        dispatch({ type: "ADD", payload: article });       // if it exists, add it to the ArticlesContext
```
Comment (ctmbl) [inline frontend/src/pages/blog/Article.js:13]: I think you should do
```suggestion
        dispatch({ type: "SET", payload: [article] }); // if it exists, add it to the ArticlesContext
```
as `SET` is defined (and used in `frontend/src/pages/blog/Blog.js`) it is the proper way to do what you are trying to do!
And it also remove the need of redefining `ADD` as you did :wink: 
@atxr

**Review by ctmbl — CHANGES_REQUESTED** [review]
Some changes but overall it simply solves a really annoying issue so thanks a lot!

File: frontend/src/pages/blog/Article.js [hunk 4]
```diff
@@ -4,9 +4,28 @@ import { useArticlesContext } from "../../hooks/useArticlesContext";
...
+      }
+      else {
+        return null;
+      } 
+  };
+  
+  try {
+    const article = articles.filter((a) => a._id === id)[0];
+    return <ArticleView article={article} />;
+  } catch (error) { //if articles are null, articles.filter produces an error
```
[the remark this answers is not in the document]
Comment (atxr) [reply frontend/src/pages/blog/Article.js:24]: What kind of error would you like to filter?

File: frontend/src/pages/blog/Article.js (hunk 3 above)
Comment (atxr) [reply frontend/src/pages/blog/Article.js:13]: No I don't think this is a good idea.
Actually if your context is not empty it will overwrite it.
Take the following example:
-> You browse an article
-> From this article, you browse another article
-> You finally go back to the first article
In this example, if you `SET`, the first article will be overwritten when browsing the second one. So the app will fetch again the first article in the third step.
I hope it makes sense :)

File: frontend/src/context/ArticleContext.js (hunk 2 above)
Comment (atxr) [reply frontend/src/context/ArticleContext.js:16]: A real *Never Nester* would opt for
```js
state.articles ??= [] 
return {articles: [action.payload, ...state.articles], };
```

File: frontend/src/pages/blog/Article.js (hunk 3 above)
Comment (gbrivady) [reply frontend/src/pages/blog/Article.js:13]: @atxr answered in my stead, if you use `SET` for some reason but there are already articles loaded in, you will overwrite everything - so definetly not a good idea

File: frontend/src/pages/blog/Article.js (hunk 1 above)
Comment (gbrivady) [reply frontend/src/pages/blog/Article.js:22]: Let's say that my "limited `JS` knowledge created this infamy 😅 fixed in 0d870937c5d299647f9a40d996205c7e7020bdf0

File: frontend/src/context/ArticleContext.js (hunk 2 above)
Comment (gbrivady) [reply frontend/src/context/ArticleContext.js]: Not exactly enlightened in `JS`, so I was unaware of all the equality stuff, but I do now 👍 fixed in 3b178585584f276ceabc0c56b954f8a59510594d

Not going to used any `??` shenanigan tho because I think it's not necessary, the nesting is not excessive I believe, so let's keep it clear 😉

File: frontend/src/pages/blog/Article.js (hunk 1 above)
Comment (atxr) [reply frontend/src/pages/blog/Article.js:22]: Perfect!

File: frontend/src/context/ArticleContext.js (hunk 2 above)
Comment (atxr) [reply frontend/src/context/ArticleContext.js]: Perfect good for me!

Comment (atxr) [reply frontend/src/context/ArticleContext.js]: I'll let @ctmbl resolve

**Review by atxr — APPROVED** [review]
🚀

File: frontend/src/pages/blog/Article.js (hunk 3 above)
Comment (ctmbl) [reply frontend/src/pages/blog/Article.js:13]: @atxr 
Ok you're right I didn't see things this way, but then, what's the whole point of *having* a `SET`?

File: frontend/src/context/ArticleContext.js (hunk 2 above)
Comment (ctmbl) [reply frontend/src/context/ArticleContext.js]: > A real Never Nester would opt for

Ow god that was exactly what I was looking for but didn't manage to find it :heart_eyes:

File: frontend/src/pages/blog/Article.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ctmbl) [reply frontend/src/pages/blog/Article.js:24]: I don't know the names of errors that can happen but you never now what can trigger an error so better be safe than sorry right? 
In `python` even if I can't *imagine* what kind of Exception could occur I would still filter it as a matter of principle :+1:

File: frontend/src/pages/blog/Article.js (hunk 1 above)
Comment (ctmbl) [reply frontend/src/pages/blog/Article.js:22]: Actually I'm wondering: why don't we need to pass `id` as parameter of `fetchArticle`?

Comment (gbrivady) [reply frontend/src/pages/blog/Article.js:22]: `id`is defined within the scop of the `Article` class (see line 1) so it already sees it

Comment (ctmbl) [reply frontend/src/pages/blog/Article.js:22]: I get it but it feels weird I guess!

File: frontend/src/pages/blog/Article.js (hunk 3 above)
Comment (atxr) [reply frontend/src/pages/blog/Article.js:13]: `SET` is used [here](https://github.com/iScsc/iscsc.fr/blob/main/frontend/src/pages/blog/Blog.js#L15)
It's used when you load the `/` route to fetch all the article.

Comment (ctmbl) [reply frontend/src/pages/blog/Article.js:13]: Yes I already saw it but now that `ADD` has been patched what's the difference between using `ADD` when empty and using `SET` (apart from the list), does it not seem confusing to you ?

Comment (atxr) [reply frontend/src/pages/blog/Article.js:13]: `ADD` adds only one article when `SET` can add multiple at the same time

File: frontend/src/pages/blog/Article.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (atxr) [reply frontend/src/pages/blog/Article.js:24]: You are right, but here, regardless the error, we should fetch the article again. 
We don't really need to switch on different type of exception, because in every case, we should fetch.

**Review by atxr — APPROVED** [review]

File: frontend/src/pages/blog/Article.js (hunk 3 above)
Comment (ctmbl) [reply frontend/src/pages/blog/Article.js:13]: Ok, I already got this point but while thinking about yesterday I finally understand why we need both, my problem was a little pointy but I get it!

File: frontend/src/pages/blog/Article.js (hunk 4 above)
[the remark this answers is not in the document]
Comment (ctmbl) [reply frontend/src/pages/blog/Article.js:24]: Ok tks for the explanation, I'm ok with it so let's go

**Review by ctmbl — APPROVED** [review]
Nice fix, and sorry for the delay :sweat_smile: let's merge it :rocket:
